site_name: Data Engineering Team 1
theme:
  name: material
  palette:
    primary: teal
  font:
    text: Krub
    code: Roboto Mono
nav:
  - Home: index.md
  - Apache Airflow:
      - apache-airflow/use.md
      - Databases: apache-airflow/databases.md
  - Docker 1:
      - docker/use.md
      - Volumes: docker/volumes.md
      - Networks: docker/networks.md
      - Images: docker/images.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
