site_name: Data Engineering Team 1
theme:
  name: material
  palette:
    primary: teal
  font:
    text: Krub
    code: Roboto Mono
nav:
  - Home: index.md
  - Apache Airflow:
      - Basics: apache-airflow/use.md
      - Databases: apache-airflow/databases.md
  - Docker 1:
      - Basics: docker1/use.md
      - Volumes: docker1/volumes.md
      - Networks: docker1/networks.md
      - Images: docker1/images.md
  - Docker 2:
      - MEA Cloud: docker2/meacloud.md
      - Networks: docker2/networks.md
      - Compose: docker2/compose.md
      - Docker Swarm: docker2/swarm.md
      - Docker Secrets: docker2/secrets.md
  - Databases:
      - PostgreSQL: databases/postgres.md
      - MongoDB: databases/mongo.md
      - Redis: databases/redis.md
      - Neo4J: databases/neo4j.md
markdown_extensions:
  # - pymdownx.highlight:
  #     anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
