site_name: Data Engineering Team 1
theme:
  name: material
  palette:
    primary: teal
  font:
    text: Krub
    code: Roboto Mono
nav:
  - Home: index.md
  - Apache Airflow:
      - apache-airflow/index.md
      - Databases: apache-airflow/databases.md
      - Source: apache-airflow/source.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
